# docker-compose.yml
version: '3.8'

services:
  voice-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - server/.env
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      - /app/node_modules
    restart: unless-stopped
    command: npm run dev

  # Nginx для продакшена
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - voice-app
    restart: unless-stopped